### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by VistaQvQ** [yuanqimanong/imgconvert-tool#1]
很好用的工具
- 希望能够支持Word格式相关文件
- 很好用的工具，建议在“关于”中增加github链接
- 如果是限定只对PDF文件转换 ，openfiledialog没必要有“所有文件｜*.*”的配置

**Comment by yuanqimanong** [comment]
很好的建议，第一点暂时可以用WPS另存为pdf文件后在进行操作，剩下的两点建议已更新
